---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: poi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poi
    spec:
      containers:
      - image: registrysuh5998.azurecr.io/tripinsights/poi:1.0
        imagePullPolicy: IfNotPresent
        name: poi
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password
        - name: SQL_SERVER
          value: 'sqlserversuh5998.database.windows.net'
        - name: SQL_DBNAME
          value: 'mydrivingDB'
        - name: WEB_PORT
          value: '80'
        - name: WEB_SERVER_BASE_URI
          value: 'http://0.0.0.0'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Local'
        - name: CONFIG_FILES_PATH
          value: '/secrets'
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: poi
  name: poi
  namespace: api
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: poi
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
data:
  password: cFc0YnAzU3M4
  username: c3FsYWRtaW5zVWg1OTk4
kind: Secret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: api
