apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 1
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrysuh5998.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service.api.svc.cluster.local:8080"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.api.svc.cluster.local:8080"

