kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-edit-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: api
  name: 79528c2b-069a-4b43-bf57-3af4ba524117
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-view-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: web
  name: 79528c2b-069a-4b43-bf57-3af4ba524117