kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-user-full-access
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-user-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-user-full-access
subjects:
- kind: Group
  name: 5ebac098-915c-49de-82ca-ccadf8a59f12
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-edit-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: web
  name: 54312d26-a38f-4825-9ded-c1427695d59d
  
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-view-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: api
  name: 54312d26-a38f-4825-9ded-c1427695d59d