apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "sqlsecret1"                # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: User
          objectType: secret              # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: password
          objectType: secret
    tenantId: "4a561f1c-6f72-4a66-b732-2075be958241"                       # the tenant ID of the KeyVault

