apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector:
    matchLabels:
      app: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registrysuh5998.azurecr.io/tripinsights/userprofile:1.0
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: User
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: SQL_SERVER
            value: "sqlserversuh5998.database.windows.net"
          - name: SQL_DBNAME
            value: "mydrivingDB"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds                 # Only required when using service principal mode. The name of the Kubernetes secret that contains the service principal credentials to access keyvault.
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
  labels:
    app: userprofile
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: userprofile